apiVersion: apps/v1
kind: Deployment
metadata:
  name: letsgetnaughty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: letsgetnaughty
  template:
    metadata:
      name: letsgetnaughty
      labels:
        app: letsgetnaughty
    spec:
      containers:
      - name: letsgetnaughty
        image: letsgetnaughty/cit270
        volumeMounts:
        - name: ssl
          mountPath: "/usr/src/app/SSL"
        command: ["npm"]
        args: ["run", "start"]
        resources:
          requests:
            cpu: .125
            memory: "500Mi"
          limits:
            cpu: .125
            memory: "600Mi"
        imagePullPolicy: Always
      volumes:
      - name: ssl
        secret:
          secretName: naughty-secrets